// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHost() {
  return window['go']['main']['App']['GetHost']();
}

export function SetHost(arg1) {
  return window['go']['main']['App']['SetHost'](arg1);
}

export function TakeScreenshot() {
  return window['go']['main']['App']['TakeScreenshot']();
}

export function WriteGame(arg1) {
  return window['go']['main']['App']['WriteGame'](arg1);
}

export function WriteSystem(arg1) {
  return window['go']['main']['App']['WriteSystem'](arg1);
}
