// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHost():Promise<string>;

export function SetHost(arg1:string):Promise<void>;

export function TakeScreenshot():Promise<void>;

export function WriteGame(arg1:string):Promise<void>;

export function WriteSystem(arg1:string):Promise<void>;
